### PR TITLE
Add scala sbt s2i

### PR DESCRIPTION
**Pull request by pdmack**
A working version of a Scala/SBT S2I builder.
- Largely cloned from RAD Java S2i
- _Opinion_ is that although we would call this a Scala S2I, it really is SBT that is the core build tool of this language image
- Spark 2.1.0, Scala 2.11.8, and SBT 0.13.13 installed
- SBT "primed" in Dockerfile to download an ivy2 repo and an SBT boot dir in /tmp
- Small SparkPi Scala test app included (actually the same one from upstream)
- Scala installed but not referenced locally atm, need to figure out the correct details for referencing the unmanaged jars locally
- "make test" fails at the end but so does the Java S2I per @tmckayus

### CODE REVIEW

**Comment by pdmack** [comment]
https://github.com/pdmack/scala-sbt-s2i-test.git added for testing purposes

**Comment by willb** [comment]
Regarding application classpaths, we should probably document that users should list Spark dependencies as `provided` so they get binaries from `openshift-spark` instead of from Maven Central.  (We'd then also need to provide a launcher skeleton that sets up a classpath for applications.)

**Comment by pdmack** [comment]
They'll also be listing their app-specific dependencies in their build.sbt. Documentation might be the only recourse if there are classpath issues/conflicts.

**Comment by elmiko** [comment]
tested out locally, worked for me.

my only suggestion is to create a `scala/README.md` with a few instructions on how i should structure my repo for building a scala app with this s2i. i think the main thing is that the repo should have a `build.sbt` file in the root.

**Comment by pdmack** [comment]
@elmiko: Yup, could do. A typical sbt project would have a build.sbt in the root directory of the repo.

**Comment by elmiko** [comment]
cool, i think just mentioning that would be sufficient for now. i just want to make sure that someone looking to use this s2i would have an idea about building their repo, it seems easy enough if you just need to dump the build.sbt in the root.

**Pull request merged**
