### PR TITLE
Spark URL override

### PR DESCRIPTION
**Pull request by elmiko**
this change set adds a new environment variable named `NONOSHINKO_SPARK_URL`, which gives users the ability to specify a spark url (eg `spark://mycluster:7077`) for their cluster.

when specified, this variable will override the usual mechanisms for cluster creation/binding and directly substitute the environment variable value to the `--master` parameter in the `spark-submit` call of `start.sh`.

the templates have been updated to allow this option as a parameter, but no additional tests have been added. i figure this is a sort of "force" option that allows users to override all the normal sanity checks.

### CODE REVIEW

**Comment by elmiko** [comment]
@tmckayus @jkremser , would love to get your thoughts on this.

**Comment by elmiko** [comment]
by way of testing, i have deployed a spark cluster with the spark operator and the launch sparkpi with the new variable set to the url from the cluster. everything seemed to work well.

**Comment by jkremser** [comment]
I like the change, it allows more flexibility for the user. Perhaps `NONOSHINKO_SPARK_URL` is little bit cryptic (what makes a regular spark cluster the oshinko one? it quacks like a spark, it's a spark :] from the spark-submit POV).

The potential issue here may be the spark version mismatch between the driver and master, which wasn't the issue before, because it was guaranteed the version will match.

**Comment by elmiko** [comment]
> I like the change, it allows more flexibility for the user. Perhaps NONOSHINKO_SPARK_URL is little bit cryptic (what makes a regular spark cluster the oshinko one? it quacks like a spark, it's a spark :] from the spark-submit POV).

this is a good point, i went with `NONOSHINKO_` to designate that the cluster originated from some other tooling that oshinko. but i also thought about calling it something like `SPARK_URL_OVERRIDE` or something. i want it to be clear you are overriding the default mechanisms and checks.

> The potential issue here may be the spark version mismatch between the driver and master, which wasn't the issue before, because it was guaranteed the version will match.

i think this is ok, i want to explicitly state the the spark url override is for custom situations. it is not supported with all the checking tooling that exists, it is essentially a form of `--force` for oshinko s2i.

**Comment by elmiko** [comment]
@jkremser i renamed the variable to `SPARK_URL_OVERRIDE`, is that more clear about its usage?

**Comment by tmckayus** [comment]
The change itself looks pretty good. It makes me wonder if the exit handling needs to be fixed up a bit. The point of the handle_term routine is to make sure that spark-submit gets killed, it has a retry because spark did not always die nicely.

But the delete_ephemeral call doesn't apply to either spark-on-k8s or your new override case. It should probably be factored out of handle_term (maybe a common handle_term loop and then an extra wrapper for the spark standalone case that calls it?)

Also thinking that spark-on-k8s should also use handle_term as the signal hander

**Comment by elmiko** [comment]
> It makes me wonder if the exit handling needs to be fixed up a bit.

this is a good point, i didn't quite understand the exit handling stuff so i didn't delve too deeply. i just tried to remove the commands that seemed inappropriate for this change.

in general, i think your impulse about cleaning up the exit handling is probably a good one.

**Pull request merged**
