### PR TITLE
SCL changes for pyspark

### PR DESCRIPTION
**Pull request by pdmack**
The base CentOS image for S2I now uses python2.7 from SCL. Thus, you must explicitly enable SCL when running pip in a layer for installing packages like numpy.

### CODE REVIEW

**Comment by GrahamDumpleton** [comment]
The ``scl_enable`` script already activates the Python virtual environment. So can probably do with just:

```
RUN source /opt/app-root/etc/scl_enable && pip install numpy
```

Can you try that.

**Comment by tmckayus** [comment]
@GrahamDumpleton 

tried that, works for me!  thanks

**Comment by pdmack** [comment]
@tmckayus all set. Thanks for the tip @GrahamDumpleton!

**Comment by tmckayus** [comment]
thanks @pdmack, @GrahamDumpleton!

**Pull request merged**
