### PR TITLE
Fix up change-yaml.sh to generate md5 sum for spark

### PR DESCRIPTION
**Pull request by tmckayus**
This is transitional while we wait for sha512 support in cekit.

### CODE REVIEW

**Comment by tmckayus** [comment]
@elmiko ptal
This is part of the in-flight spark 2.4 update

**Comment by tmckayus** [comment]
is that part of cekit 3? if so we need to modify the image.yamls, we can do that all at once

**Comment by elmiko** [comment]
looks like my changes are in cekit 3.1 for sure, so maybe we should just proceed as is and leave the todos for later.

**Comment by tmckayus** [comment]
Merging before tests complete, this is just a utility script

**Pull request merged**
