### PR TITLE
Add default spark configs to driver that match openshift-spark

### PR DESCRIPTION
**Pull request by tmckayus**
This change adds the same default spark configs to driver images
generated through s2i as are included in openshift-spark. These
configs can still be overridden via a configmap or spark-conf
directory co-located with source code.

### CODE REVIEW

**Comment by mattf** [comment]
are there any case where we would not want to have the reverseproxy configured?

if not, does providing a configmap overwrite the default reverseproxy? does providing a spark-conf overwrite the default?

**Comment by tmckayus** [comment]
Adding an additional patch for this, in which the reverse proxy settings will be appended to the spark-defaults.conf after all updates from configmap/git assuming there are not already reverse proxy settings in spark-defaults.conf.

With this, the default settings will always be provided by oshinko code/images unless a user has explicitly set them (to turn it off for some reason, or change the endpoint for some reason.  Not sure why that might happen, but this preserves control)

**Comment by tmckayus** [comment]
@matt ptal

**Comment by mattf** [comment]
lftm

**Pull request merged**
