### PR TITLE
setup dockerfile to allow auto-builds in docker hub

### PR DESCRIPTION
**Pull request by mattf**

### CODE REVIEW

**Comment by mattf** [comment]
@tmckayus ptal

**Comment by tmckayus** [comment]
The Dockerfile.pyspark is working for me using "docker build -f Dockerfile.pyspark" and pushing.

However, changes to the Makefiles are needed.

Since the oshinko-get-cluster utility is being built in the image, it doesn't need to be a dep for the image anymore.  It can still optionally be built locally for testing, etc.

And the Makefile in ./pyspark is still looking for a local Makefile.

**Comment by mattf** [comment]
@tmckayus ptal, i addressed the build & test targets

**Comment by mattf** [comment]
@elmiko the re-org of the dockerfile in this pr is required for the travis-ci integration in #36, so #36 is based off this pr. merge this pr first.

**Comment by elmiko** [comment]
ack, i'm gonna let Trevor merge this one as he had the request for changes.

**Comment by tmckayus** [comment]
lgtm, thanks matt!

**Pull request merged**
