### PR TITLE
Break up end-to-end tests into separate scripts

### PR DESCRIPTION
**Pull request by tmckayus**
This change breaks up the tests in test/cmd/ephemeral/ephemeral.sh
into individual tests grouped into directories and adds a
test runner in test/e2e/run.sh based on the original
hack/test-cmd.sh (which is no longer used)

* Ephemeral cluster tests are in test/e2e/ephemeral
* Incomplete cluster tests are in test/e2e/incomplete
* Common functions are in test/e2e/common
* Common resources are in test/e2e/resources
* Make has been changed to use test/e2e/run.sh
* The hack subdir is a partial copy from OpenShift Origin, the
  tests herein use a subset of the framework but do not use
  any test runners from hack or build any local binaries.

### CODE REVIEW

**Comment by elmiko** [comment]
i tried this out against my local cluster and i see some strangeness in the output. i don't think it succeeded on the whole although some parts did succeed.

my setup
```
$ oc version
oc v3.6.0-rc.0+49df2d6-242
kubernetes v1.7.0+695f48a16f
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://127.0.0.1:8443
openshift v3.6.0-rc.0+98b3d56
kubernetes v1.6.1+5115d708d7
```

steps to reproduce
1. checkout tmckayus/oshinko-s2i:finalsplittest
1. run `make test-e2e` from root of that repor

results included in attached file
[test-e2e.log.txt](https://github.com/radanalyticsio/oshinko-s2i/files/1171181/test-e2e.log.txt)

**Comment by elmiko** [comment]
i ran these tests again with a different version of openshift

```
$ oc version
oc v3.6.0-rc.0+49df2d6-242
kubernetes v1.7.0+695f48a16f
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://127.0.0.1:8443
openshift v1.5.1+7b451fc
kubernetes v1.5.2+43a9be4
```

but i still produced at least one failure. i'm including the logs
[test-e2e.v1.5.1.log.txt](https://github.com/radanalyticsio/oshinko-s2i/files/1171241/test-e2e.v1.5.1.log.txt)

**Comment by tmckayus** [comment]
Quick look, a few things happened

1) I need to randomize the dc names, as we chatted about earlier.  In this case something went wrong with the first scale test. The spark master dc, did not appear after 2 minutes could be related to #3 below. In any case, many of the other tests failed in the same project because the driver dc "bob" already existed.  Either randomize, or see if the error can be caught in a test and the current dcs wiped out.

2) Script is using "oc log" instead of "oc logs" and this gave a lot of deprecation warnings. Easy to fix.

3) This is the interesting one, and may explain why #1 failed.  The message on create that "--app" is an unknown flag is really strange. It means that the version of the CLI that was in the built image is not correct, I believe.  This would make all of the tests fail, which I think is the real problem with this run.

I think it came from this:

[91mfatal: destination path 'oshinko-cli' already exists and is not an empty directory.
make[1]: [oshinko-cli] Error 128 (ignored)

If this wasn't a fresh checkout of oshinko-s2i, and there was a CLI binary already in the source tree, that would explain it. Perhaps I ought to add a "clean" element to "make test-e2e" to make sure there is no CLI artifact.

**Comment by elmiko** [comment]
i ran this again with a clean checkout against my 1.5.1 cluster and it succeeded.

logs in attached file
[test-e2e-2017-25-17-1.v1.5.1.log.txt](https://github.com/radanalyticsio/oshinko-s2i/files/1173468/test-e2e-2017-25-17-1.v1.5.1.log.txt)

**Comment by elmiko** [comment]
i re-ran the latest version and everything seems to be working locally

tested with
```
$ oc version
oc v3.6.0-rc.0+49df2d6-242
kubernetes v1.7.0+695f48a16f
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://shift.opb.studios:8443
openshift v1.5.1+7b451fc
kubernetes v1.5.2+43a9be4
```

results attached
[test-e2e-2017-07-27-1.v1.5.1.log.txt](https://github.com/radanalyticsio/oshinko-s2i/files/1181100/test-e2e-2017-07-27-1.v1.5.1.log.txt)

**Pull request merged**
